name: Build and Run Docker

on: [push]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t website .
    
    - name: Run Docker container
      run: docker run -d --name website -p 80:80 website
